version: '3'

services:
  db:
    image: postgres
  webpacker:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/ondeeunb
    ports:
      - "3035:3035"

  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/ondeeunb
    ports:
      - "3000:3000"
    depends_on:
      - db
      - webpacker
